### ISSUE TITLE
I did not find this file 

### ISSUE THREAD

**Issue by Ehab09** [PietroMSB/DrugSideEffects#1]
https://github.com/PietroMSB/DrugSideEffects/blame/ac8d5cf1413d3786ea446b7e73496cc36ee909d8/Datasets/Nuovo/extract_dataset.py#L15

**Comment by PietroMSB** [comment]
Dear Ehab09,

Thank you very much for pointing this out. I am sorry, I had forgotten to mention this fact in the readme: STITCH is too large to be uploaded in the GitHub repo, so you will need to download it from the following link and put the contents inside the new Dataset/Nuovo/STITCH folder which I just created: http://stitch.embl.de/

I added this information to the readme and also added some other files which were missing (Gene Features)

Let me know if everything works,

Best,
Pietro
