### ISSUE TITLE
I did not find these dependencies on Git.

### ISSUE THREAD

**Issue by Ehab09** [PietroMSB/DrugSideEffects#2]
Graph Neural Networks are implemented with the GNN software described here: https://github.com/NickDrake117/GNN_tf_2.x

Composite Graph Neural Networks are implemented with this repository: https://github.com/NickDrake117/CompositeGNN

Are they implemented within the project or are they ready-made data whose results are used in the project and there is no need to implement them?

In addition, what is meant by Soglia_10 , Soglia_100 and Soglia_50 files inside Dataset -> Nuovo -> Output file ?

Best great.

**Comment by PietroMSB** [comment]
Dear Ehab09,

Thank you very much for letting me know. I hadn't opened them in a while,
Concerning the GNN software, GNN_tf2 has been replaced with the GNN_keras repo: [](https://github.com/NickDrake117/GNNkeras)
For the Composite GNNs, I think you can find the same version of the software in my CGNN repo: [](https://github.com/PietroMSB/CompositeGNN_OGB_Experimentation)
 
If something doesn't work with these two, I think I can find the precise software version I used and add it to this repo.

Actually, they are just GNN libraries, so there is no need to implement them, they are just used in the code.

Soglia_10, Soglia_50 and Soglia_100 are three output files I obtained by changing the frequency threshold for side-effects. For instance, in the Soglia_10 experiment, I took every side-effect  which is assoiated to at least 10 drugs in SIDER. In the Soglia_50, I took all the side-effects that are associated to at least 50 drugs in SIDER, and so on...

I will add this information to the readme.

Best,
Pietro
